variables:
  GIT_SUBMODULE_STRATEGY: recursive
 
stages:
 - build
 
buildMacOS:
  stage: build
  before_script:
    - cd desktop
    - yarn install
    - cd app
    - yarn install
    - cd ..
    - cd ..
  script:
    - cd desktop
    - gulp publishCurrentPlatform
    - cd ..
  artifacts:
    paths:
    - dist
  only:
   - master
   - develop
  tags:
    - macOS

buildWindows:
  stage: build
  before_script:
    - cd desktop
    - call yarn install
    - cd app
    - call yarn install
    - cd ..
    - cd ..
  script:
    - cd desktop
    - call gulp publishCurrentPlatform
    - cd ..
  artifacts:
    paths:
    - dist
  only:
    - master
    - develop
  tags:
    - windows
    
buildLinux:
  stage: build
  before_script:
    - cd desktop
    - yarn install
    - cd app
    - yarn install
    - cd ..
    - cd ..
  script:
    - cd desktop
    - gulp publishCurrentPlatform
    - cd ..
  artifacts:
    paths:
    - dist
  only:
   - master
   - develop
  tags:
    - linux
