variables:
  GIT_SUBMODULE_STRATEGY: recursive
 
stages:
 - build
 
buildMacOS:
  stage:
   - build
  before_script:
    - cd desktop
    - npm install
    - cd ..
  script:
    - cd desktop
    - ALLOW_ELECTRON_BUILDER_AS_PRODUCTION_DEPENDENCY=true gulp
    - cd ..
  artifacts:
    paths:
    - dist
  only:
   - master
  tags:
    - macOS

#buildWindows:
# script:
#    - cd desktop
#    - call npm install
#    - call gulp
#    - cd ..
#  artifacts:
#    paths:
#    - dist
#  tags:
#    - windows
    
#buildLinux:
#  before_script:
#    - cd desktop
#    - npm install
#    - cd .. 
#  script:
#    - cd desktop
#    - gulp
#    - cd ..
#  artifacts:
#    paths:
#    - dist
#  tags:
#    - linux
