variables:
  GIT_SUBMODULE_STRATEGY: recursive
 
stages:
 - test
 - build
 
testMacOS:
  stage: test
  before_script:
    - cd desktop
    - yarn install
    - cd ..
  script:
    - cd desktop
    - yarn test
    - cd ..
  tags:
    - macOS
    
testLinux:
  stage: test
  before_script:
    - cd desktop
    - yarn install
    - cd ..
  script:
    - cd desktop
    - cd ..
  tags:
    - linux
    
testWindows:
  stage: test
  before_script:
    - cd desktop
    - call yarn install
    - cd ..
  script:
    - cd desktop
    - call yarn test
    - cd ..
  tags:
    - windows
    
buildMacOS:
  stage: build
  before_script:
    - cd desktop
    - yarn install
    - cd ..
  script:
    - cd desktop
    - gulp publishCurrentPlatform
    - cd ..
  artifacts:
    paths:
    - dist
  only:
   - master
   - develop
  tags:
    - macOS

buildWindows:
  stage: build
  before_script:
    - cd desktop
    - call yarn install
    - cd ..
  script:
    - cd desktop
    - call gulp publishCurrentPlatform
    - cd ..
  artifacts:
    paths:
    - dist
  only:
    - master
    - develop
  tags:
    - windows
    
buildLinux:
  stage: build
  before_script:
    - cd desktop
    - yarn install
    - cd ..
  script:
    - cd desktop
    - gulp publishCurrentPlatform
    - cd ..
  artifacts:
    paths:
    - dist
  only:
   - master
   - develop
  tags:
    - linux
