variables:
  GIT_SUBMODULE_STRATEGY: recursive
 
stages:
 - test
 - build
 
testMacOS:
  stage: test
  before_script:
    - cd desktop
    - yarn install
    - cd ..
  script:
    - cd desktop
    - yarn test
    - cd ..
  tags:
    - macOS
    
testWindows:
  stage: test
  before_script:
    - cd desktop
    - call yarn install
    - cd ..
  script:
    - cd desktop
    - call yarn test
    - cd ..
  tags:
    - windows

buildMacOS:
  stage: build
  before_script:
    - cd desktop
    - yarn install
    - cd ..
  script:
    - cd desktop
    - gulp buildCurrentPlatform
    - cd ..
  artifacts:
    paths:
    - dist
  only:
   - master
   - develop
  tags:
    - macOS
  except:
    - tags

buildWindows:
  stage: build
  before_script:
    - cd desktop
    - call yarn install
    - cd ..
  script:
    - cd desktop
    - call gulp buildCurrentPlatform
    - cd ..
  artifacts:
    paths:
    - dist
  only:
    - master
    - develop
  tags:
    - windows
  except:
    - tags
    
buildLinux:
  stage: build
  before_script:
    - cd desktop
    - yarn install
    - cd ..
  script:
    - cd desktop
    - gulp buildCurrentPlatform
    - cd ..
  artifacts:
    paths:
    - dist
  only:
   - master
   - develop
  tags:
    - linux
  except:
    - tags

publishMacOS:
  stage: build
  before_script:
    - cd desktop
    - yarn install
    - cd ..
  script:
    - cd desktop
    - gulp buildCurrentPlatform
    - cd ..
  artifacts:
    paths:
    - dist
  only:
   - master
   - develop
  tags:
    - macOS
  only:
    - tags
    
publishWindows:
  stage: build
  before_script:
    - cd desktop
    - call yarn install
    - cd ..
  script:
    - cd desktop
    - call gulp publishCurrentPlatform
    - cd ..
  artifacts:
    paths:
    - dist
  only:
    - master
    - develop
  tags:
    - windows
  only:
    - tags
    
publishLinux:
  stage: build
  before_script:
    - cd desktop
    - yarn install
    - cd ..
  script:
    - cd desktop
    - gulp publishCurrentPlatform
    - cd ..
  artifacts:
    paths:
    - dist
  only:
   - master
   - develop
  tags:
    - linux
  only:
    - tags
    